#10-task-1
JPerzanowski/Java pull request #4
Opened 2022-07-25 13:51 UTC by JPerzanowski

2022-07-25 15:09 UTC, JaRutkowski commented on src/com/javafee/tasks/task1/Main.java
> +        int[] reverse = new int[num];
Could u please try to do it without using array? :)

2022-07-25 15:09 UTC, JaRutkowski commented on src/com/javafee/tasks/task1/Main.java
> +//        int num = new Scanner(System.in).nextInt();
What is that code for?

2022-07-25 15:11 UTC, JaRutkowski requested changes
PSB (comments)

2022-07-25 20:11 UTC, JPerzanowski commented on src/com/javafee/tasks/task1/Main.java
> +        int[] reverse = new int[num];
I did it

2022-07-25 20:12 UTC, JPerzanowski commented on src/com/javafee/tasks/task1/Main.java
> +//        int num = new Scanner(System.in).nextInt();
It shows an amount of numbers in a row

2022-07-26 19:02 UTC, JaRutkowski commented on src/com/javafee/tasks/task1/Main.java
> +//        int num = new Scanner(System.in).nextInt();
Is it needed - as it is the comment only? IMO all comments should be removed.

2022-07-26 19:24 UTC, JPerzanowski commented on src/com/javafee/tasks/task1/Main.java
> +//        int num = new Scanner(System.in).nextInt();
Sorry, I didn't notice it's a comment.

2022-07-26 20:43 UTC, JaRutkowski requested changes
PSB (comments)

2022-07-26 20:43 UTC, JaRutkowski commented on src/com/javafee/tasks/task1/Main.java
> +            for (int i = 1, k = 2 + count, x = 4 + count, p = 1; i <= (2 * num) + 1; i++)
I'm sure that it's possible to make it without such many if instructions, please try to do it in a more simple way (without many if's).

2022-07-26 20:44 UTC, JaRutkowski commented on src/com/javafee/tasks/task1/Main.java
> +            for (int i = 1, k = 2 + count, x = 4 + count, p = 1; i <= (2 * num) + 1; i++)
I'll try to give u some examples, maybe not fully done, but something that will help u in the further implementation.

2022-07-27 19:34 UTC, JaRutkowski commented on src/com/javafee/tasks/task1/Main.java
> +            for (int i = 1, k = 2 + count, x = 4 + count, p = 1; i <= (2 * num) + 1; i++)
Did u have a chance to look at it?

2022-07-27 19:37 UTC, JaRutkowski requested changes
Line 57 - unnecessary brackets. 
Line 147 - is it possible to move k/p to loop and then use the ternary operator?
Line 154 - unnecessary comment.
// Task 10 - what is the status?

2022-07-27 19:47 UTC, JPerzanowski commented on src/com/javafee/tasks/task1/Main.java
> +            for (int i = 1, k = 2 + count, x = 4 + count, p = 1; i <= (2 * num) + 1; i++)
I will do it right now.

2022-08-01 04:57 UTC, JaRutkowski approved these changes
Please merge and create the 'bug' type issues for the improvements.

2022-08-01 04:59 UTC, merged